name: test
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

env:
  JULIA_LANGSERVER: 3.2.0
jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.6'
      
      - name: Install Julia language server
        run: julia -e 'using Pkg; Pkg.add(Pkg.PackageSpec(;name="LanguageServer", version="${{ env.JULIA_LANGSERVER }}"))'
